name: open_weather_application
description: A Flutter project for open weather.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.2
  geolocator: ^7.2.0+1
  provider: ^6.0.3
  easy_localization: ^3.0.1
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true 
  generate: true
  
  assets:
    - assets/.env
    - assets/images/app.png